# Generated by Django 5.1.11 on 2026-03-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0058_annotation_project_completed_by_cancelled_idx"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="annotation",
            new_name="task_comple_project_b874c4_idx",
            old_name="tsk_ann_prj_usr_can_idx",
        ),
    ]
