# Generated by Django 5.1.11 on 2026-03-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels_manager", "0003_auto_20221213_1612"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labellink",
            options={"ordering": ["id"]},
        ),
    ]
