# Generated by Django 5.1.10 on 2025-08-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_project_search_vector_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="challenge_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional challenge id for project integration.",
                max_length=255,
                null=True,
                verbose_name="challenge id",
            ),
        ),
    ]
