# Generated by Django 5.1.10 on 2025-08-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_project_challenge_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="participants",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of participant usernames",
                null=True,
                verbose_name="participants",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="round",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Round number of the challenge.",
                null=True,
                verbose_name="round",
            ),
        ),
    ]
