# Generated by Django 5.1.10 on 2025-08-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0032_project_participants_project_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="challenge_status",
            field=models.BooleanField(
                default=True,
                help_text="True means active; False means not active.",
                verbose_name="challenge status",
            ),
        ),
    ]


